export const characterJavaneseLabels: { icon: string; label: string }[] = [
	{ icon: 'a', label: 'HA' },
	{ icon: 'n', label: 'NA' },
	{ icon: 'c', label: 'CA' },
	{ icon: 'r', label: 'RA' },
	{ icon: 'k', label: 'KA' },
	{ icon: 'f', label: 'DA' },
	{ icon: 't', label: 'TA' },
	{ icon: 's', label: 'SA' },
	{ icon: 'w', label: 'WA' },
	{ icon: 'l', label: 'LA' },
	{ icon: 'p', label: 'PA' },
	{ icon: 'd', label: 'DHA' },
	{ icon: 'j', label: 'JA' },
	{ icon: 'y', label: 'YA' },
	{ icon: 'v', label: 'NYA' },
	{ icon: 'm', label: 'MA' },
	{ icon: 'g', label: 'GA' },
	{ icon: 'b', label: 'BA' },
	{ icon: 'q', label: 'THA' },
	{ icon: 'z', label: 'NGA' }
];

export const characterSundaneseLabels: { icon: string; label: string }[] = [
	{ icon: 'k', label: 'KA' },
	{ icon: 'n', label: 'GA' },
	{ icon: 'c', label: 'NGA' },
	{ icon: 'r', label: 'CA' },
	{ icon: 'i', label: 'JA' },
	{ icon: 'Y', label: 'NYA' },
	{ icon: 't', label: 'TA' },
	{ icon: 'd', label: 'DA' },
	{ icon: 'n', label: 'NA' },
	{ icon: 'p', label: 'PA' },
	{ icon: 'b', label: 'BA' },
	{ icon: 'm', label: 'MA' },
	{ icon: 'y', label: 'YA' },
	{ icon: 'r', label: 'RA' },
	{ icon: 'l', label: 'LA' },
	{ icon: 'w', label: 'WA' },
	{ icon: 's', label: 'SA' },
	{ icon: 'h', label: 'HA' },
	{ icon: 'f', label: 'FA' },
	{ icon: 'v', label: 'VA' },
	{ icon: 'q', label: 'QA' },
	{ icon: 'x', label: 'XA' },
	{ icon: 'z', label: 'ZA' }
];
